{{- if not (empty .Values.swirl.secret.envSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "swirl.name" $) "env-secrets" | quote }}
  namespace: {{ default (include "swirl.name" $) .Values.namespace | quote }}
  labels:
    {{ include "common.labels" $ | nindent 4 }}
data:
{{- range $key, $value := .Values.swirl.secret.envSecrets }}
  {{ $key | nindent 2 }}: {{ $value | b64enc | quote }}
{{- end }}
#{{- with .Values.swirl.secret.envSecrets }}
#  {{- toYaml . | nindent 2 }}
#{{- end }}
{{- end }}