name: Manual Chart Release

on:
  workflow_dispatch:
    inputs:
      chart:
        description: 'Chart name to release (leave empty for all charts)'
        required: false
        type: string
      version:
        description: 'Chart version (leave empty to use Chart.yaml version)'
        required: false
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update chart version (if specified)
        if: ${{ github.event.inputs.version != '' && github.event.inputs.chart != '' }}
        run: |
          CHART_PATH="charts/${{ github.event.inputs.chart }}"
          if [ -f "${CHART_PATH}/Chart.yaml" ]; then
            sed -i "s/^version:.*/version: ${{ github.event.inputs.version }}/" "${CHART_PATH}/Chart.yaml"
            git add "${CHART_PATH}/Chart.yaml"
            git commit -m "chore: bump ${{ github.event.inputs.chart }} to version ${{ github.event.inputs.version }}"
            git push
          else
            echo "Chart ${CHART_PATH} not found!"
            exit 1
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          config: .github/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: false

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4